# Generated by Django 5.2.3 on 2025-07-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Премия'),
        ),
        migrations.AddField(
            model_name='employee',
            name='fixed_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Оклад'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_fixed_salary',
            field=models.BooleanField(default=False, verbose_name='Окладная оплата'),
        ),
    ]
