# Generated by Django 5.2.3 on 2025-07-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_employee_bonus_employee_fixed_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='for_salary_based',
            field=models.BooleanField(default=False),
        ),
    ]
