# Generated by Django 5.2.3 on 2025-07-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_workschedule_overtime_hours_workschedule_partial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='partial_day_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ставка неполной дневной смены'),
        ),
        migrations.AddField(
            model_name='department',
            name='partial_night_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ставка неполной ночной смены'),
        ),
    ]
