# Generated by Django 5.2.3 on 2025-07-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_department_partial_day_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='partial_day_rate',
        ),
        migrations.RemoveField(
            model_name='department',
            name='partial_night_rate',
        ),
        migrations.RemoveField(
            model_name='workschedule',
            name='overtime_hours',
        ),
        migrations.RemoveField(
            model_name='workschedule',
            name='partial',
        ),
        migrations.AddField(
            model_name='employee',
            name='partial_shift_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ставка неполной смены'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='shift',
            field=models.CharField(choices=[('partial', 'Неполная'), ('day', 'День'), ('night', 'Ночь'), ('weekend', 'Выходной'), ('vacation', 'Отпуск'), ('sick', 'Больничный')], max_length=10),
        ),
    ]
